version: "3.9"

networks:
  bblc_van:
    driver: bridge
    name: bblc_van_net

services:
  webserver_prd:
    image: nginx
    container_name: van_webserver_prd
    restart: unless-stopped
    tty: true
    ports:
      - 6100:80
    volumes:
      - ./api:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_prd
    networks:
      - bblc_van

  api_prd:
    build:
      context: ./
      dockerfile: ./.docker/php/Dockerfile
    container_name: van_api_prd
    working_dir: /var/www/html
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./api:/var/www/html
      - /var/www/html/vendor
    networks:
      - bblc_van
    environment:
      - TZ=Asia/Manila

  app_prd:
    build:
      context: ./
      dockerfile: ./.docker/next/Dockerfile
      target: app_prod
    container_name: van_app_prd
    stdin_open: true
    tty: true
    ports:
      - "6210:6210"
    volumes:
      - ./app:/var/www/html
      - /var/www/html/node_modules
    depends_on:
      - api_prd
    networks:
      - bblc_van
